# Generated by Django 5.2.4 on 2025-08-20 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='item',
            name='review_count',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Items.category'),
        ),
    ]
