# Generated by Django 5.2.4 on 2025-08-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_category_remove_item_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='features',
            field=models.TextField(),
        ),
    ]
